# Site settings
title: "Lau's Blog"
email: your-email@example.com
description: >-
  A technical blog documenting learning notes and insights in AI, Machine Learning, and Deep Learning.
baseurl: ""
url: "http://localhost:4000"
twitter_username: 
github_username: lausen001

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination disabled for local development

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _config_local.yml

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Lausen"
  - scope:
      path: ""
    values:
      layout: "default"

# Site configuration
show_excerpts: true
date_format: "%B %d, %Y"

# Navigation
navigation:
  - name: "Posts"
    link: "/"
  - name: "Archive"
    link: "/archive/"
  - name: "About"
    link: "/about/" 