# Site settings
title: "Lau's Blog"
baseurl: ""
url: "https://lausen001.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /posts/:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Lausen"
  - scope:
      path: ""
    values:
      layout: "default"

# Site configuration
show_excerpts: true
date_format: "%B %d, %Y"

# Navigation
navigation:
  - name: "Posts"
    link: "/"
  - name: "Archive"
    link: "/archive/"
  - name: "About"
    link: "/about/"
